version: '3'

volumes:
  qlot:

services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
      - qlot:/app/.qlot
    ports:
      - "4005:4005"
      - "3000:3000"
    tty: true
    entrypoint: qlot exec clackup -s utopian --server woo --address 0.0.0.0 --port 3000 --swank-interface 0.0.0.0 --swank-port 4005 app.lisp
