version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "app"
    ports:
      - "3000:3000"
    entrypoint: clackup --address 0.0.0.0 --port 3000 app.lisp
