version: '3'

volumes:
  qlot:
  database:

services:
  database:
    container_name: postgres
    image: postgres:15.1
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
      - qlot:/app/.qlot
    ports:
      - "4005:4005"
      - "3000:3000"
    tty: true
    entrypoint: qlot exec clackup -s test-app --server woo --address 0.0.0.0 --port 3000 --swank-interface 0.0.0.0 --swank-port 4005 app.lisp
